version: '3.8'

services:
  cryptoserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5237:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - Encryption__Key=YourSecretKey123!@#
      - AllowedIps__0=127.0.0.1
      - AllowedIps__1=::1
      - AllowedIps__2=172.17.0.1
      - AllowedIps__3=172.19.0.0/16
      - AllowedIps__4=::ffff:172.19.0.0/112
    restart: unless-stopped 